### ISSUE TITLE
.Net Core 2.0 compatibility

### ISSUE THREAD

**Issue by barissonmez** [sarathkcm/Pluralize.NET#1]
Getting this: 
Warning	NU1701	Package 'Pluralize.NET 0.1.43' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by sarathkcm** [comment]
Thanks for raising this issue 😃, I will fix it asap.
I think there won't be any compatibility issues even though you are being shown a warning. So I guess you could go ahead and use it until this is fixed.

**Comment by sarathkcm** [comment]
PR #2 Fixes this.
