### ISSUE TITLE
Zoon /zoan - broken

### ISSUE THREAD

**Issue by ErikEJ** [sarathkcm/Pluralize.NET#11]
[TestCase("protozoon", "protozoa")]
        [TestCase("spermatozoan", "spermatozoa")]
        [TestCase("hydrozoan", "hydrozoa")]

**Comment by sarathkcm** [comment]
Raise issue in original library [https://github.com/blakeembrey/pluralize/issues/142](https://github.com/blakeembrey/pluralize/issues/142)

**Comment by sarathkcm** [comment]
Raised issue in original library [https://github.com/blakeembrey/pluralize/issues/142](https://github.com/blakeembrey/pluralize/issues/142)
