### ISSUE TITLE
Singularize corpora

### ISSUE THREAD

**Issue by ErikEJ** [sarathkcm/Pluralize.NET#12]
[TestCase("corpora", "corpus")] - but get corpora

**Comment by sarathkcm** [comment]
Currently corpus is being pluralized into corpuses. While both corpora and corpuses both are correct, I think adding an irregular rule to pluralize corpus into corpora by default will solve this problem.

I will raise the same issue in the original java-script library, and will follow the same approach they follow, as we plan to keep the behavior same as the original library.

**Comment by sarathkcm** [comment]
[Raised issue here](https://github.com/blakeembrey/pluralize/issues/141)
