### ISSUE TITLE
Incorrect singularization - "miscellaneous"

### ISSUE THREAD

**Issue by stuartd** [sarathkcm/Pluralize.NET#16]
This is singularized to 'miscellaneou'

**Comment by sarathkcm** [comment]
Which version of the library are you using?

In the latest version, I'm getting correct results. Can you please update the version and try?

![image](https://user-images.githubusercontent.com/14143311/97732226-39e01680-1afc-11eb-9c3c-a328aab4390d.png)
![image](https://user-images.githubusercontent.com/14143311/97732261-4bc1b980-1afc-11eb-8269-bc173de12026.png)

**Comment by sarathkcm** [comment]
Hm. I am able to reproduce it in version 0.1.84. Please upgrade.

I'll close the issue if that works.

![image](https://user-images.githubusercontent.com/14143311/97732578-ba9f1280-1afc-11eb-9205-bc32450e375b.png)

**Comment by stuartd** [comment]
Just realised I'm was using a fork that's compatible with .Net Standard and hasn't been updated. Sorry about that.

As Pluralize.Net 1.0.2 is dotnet core compatible, I've switched to using that, and it does indeed fix the issue.

Many thanks for your response, and indeed for maintaining this project, which is very useful to us!
