### ISSUE TITLE
Pluralize Words Endings With Numbers

### ISSUE THREAD

**Issue by dogac00** [sarathkcm/Pluralize.NET#17]
`pluralizer.Pluralize("Foo1")` gives me "Foo1S" with capital 'S' at the end. I think it is better to pluralize it with lowercase 's'. I expect this: "Foo1s".

**Comment by sarathkcm** [comment]
I wouldn't consider this a defect as Foo1 is not a real word. However, I'll take a look at this, in the interest of keeping behavior the same as the original library which gives Foo1s as the plural for Foo1.

**Comment by sarathkcm** [comment]
Seems to be working as expected for me. Please update to the latest version 1.0.2. 

Also please make sure you are using the correct library from nuget. (Ref: https://github.com/sarathkcm/Pluralize.NET/issues/16#issuecomment-719708405).

Please close the issue once it works for you.

![image](https://user-images.githubusercontent.com/14143311/101235918-a13c4800-36f2-11eb-9fe2-0d2861f4d7c7.png)
