### ISSUE TITLE
Check if given word is in singular or plural form

### ISSUE THREAD

**Issue by cezarypiatek** [sarathkcm/Pluralize.NET#3]
Hi

At first I must say this really good library, you made a good job. I'm going to use it in my https://github.com/cezarypiatek/MappingGenerator project to generate lambda parameter's name for mapping collection. 

Is there an option to add method that test given word if it is plural or singular form? Something like:

```
public bool IsSingularl(string word)
{
   //TODO
}

public bool IsPlural(string word)
{
   //TODO
}
```

**Comment by sarathkcm** [comment]
Hi @cezarypiatek ,

If you try to convert an already plural word into its pural form, the library will just return the input word. 

Therefore your methods can be written as:

```csharp
public bool IsSingularl(string word)
{
   var _pluralizer = new Pluralizer();
   return _pluralizer.Singularize(word) == word; // Probably do an ignorecase comparison
}

public bool IsPlural(string word)
{
   var _pluralizer = new Pluralizer();
   return _pluralizer.Pluralize(word) == word; // Probably do an ignorecase comparison
}
```

This behaviour is verified for all the 588 unit test inputs.

Please let me know if it works out for you.

**Comment by cezarypiatek** [comment]
Hi @sarathkcm,

Thanks for response, I've tested your solution and it works like a charm. I think it would be helpful for others if you could add these two methods to `Pluralizer` class.

**Comment by sarathkcm** [comment]
Thank you for testing it @cezarypiatek :) 

I will sure add it to the class.

**Comment by sarathkcm** [comment]
Feature added in https://github.com/sarathkcm/Pluralize.NET/pull/14
