### ISSUE TITLE
Pluralization of word "index" 

### ISSUE THREAD

**Issue by kmolerov** [sarathkcm/Pluralize.NET#4]
pluralizationService.Pluralize("index"); 
expected result: **indexes**
actual result: **indices**

**Comment by kmolerov** [comment]
After reading https://business.nasdaq.com/marketinsite/2016/indexes-or-indices-whats-the-deal.html
It turned out that **indices** is also correct. So it will be convenient to configure the needed value, when the word supports two pluralization forms.

**Comment by sarathkcm** [comment]
@kmolerov How do you suggest we can make this configurable?

**Comment by kmolerov** [comment]
In Humanizer library there is similar functionality Vocabularies.Default.AddIrregular("index", "indexes");
I think something similar will be sufficient in most of the cases. But it will be nice that such configuration is not put in Irregular rules, as this is something different.

**Comment by sarathkcm** [comment]
https://github.com/sarathkcm/Pluralize.NET/pull/14 added `AddIrregularRule` method to Pluralizer, along with configuration option for other rules as well.

> But it will be nice that such configuration is not put in Irregular rules, as this is something different.

I see your point here, however there was already an `AddIrregularRule` methpd in the original library which has been ported here now with https://github.com/sarathkcm/Pluralize.NET/pull/14, and it suits well for such needs. Therefore, I think a new method which does exactly the same thing behind the scenes is not really neccesary.
